spring.application.name=WeatherProject
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/weatherdb
spring.datasource.username=postgres
spring.datasource.password=CredAi@abhinav
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
weather.api.key=${API_KEY}
weather.api.base-url=https://api.openweathermap.org
weather.api.connect-timeout=5s
weather.api.read-timeout=10s
#5 mins
jwt.access-token-expiration=300000000
#8 hrs
jwt.refresh-token-expiration=28800000
logging.level.root=INFO
logging.level.com.example.demo=INFO
cors.allowed-origins=http://localhost:5173